#!/bin/bash

# simplify directory structure by removing everything but the vignettes and binder

## remove the files
find . -type f -maxdepth 1 -delete

## move vignettes to main directory
mv vignettes/* ./

## remove folders
rm -rf R docs inst man tests vignettes

# convert RMarkdown files to ipynb
pip install ipyrmd
for f in *.Rmd; do ipyrmd $f; done

# install jupyter notebook toc
jupyter labextension install @jupyterlab/toc

# write new README
echo $'# Instructions\n\nExplore this package on binder by modifying the vignettes in RStudio (RMarkdown .Rmd files) or Jupyter Lab (notebook .ipynb files) or by creating a new notebook from scratch.' > README.md

